/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import * as THREE from 'three';

const DemoComputer = (props) => {
  const group = useRef();
  const [isMobile, setIsMobile] = useState(false);
  const { nodes, materials } = useGLTF('/models/scene.gltf');
  const videoTexture = useVideoTexture(props.texture);

  // Check if device is mobile
  useEffect(() => {
    const checkIsMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    
    checkIsMobile();
    window.addEventListener('resize', checkIsMobile);
    
    return () => window.removeEventListener('resize', checkIsMobile);
  }, []);

  // Let the glTF loader use the textures referenced inside `scene.gltf`. Only tweak material properties
  // that cause visible problems in the viewer (e.g. excessive emissive).
  useEffect(() => {
    if (!materials || !materials['01___Default']) return;
    const mat = materials['01___Default'];

    // Ensure emissive doesn't wash out the baseColor (the glTF here contains an emissiveFactor of [1,1,1])
    if (mat.emissive) mat.emissive.setHex(0x000000);

    // Ensure color textures render with correct encoding if they exist
    if (mat.map) mat.map.encoding = THREE.sRGBEncoding;

    mat.needsUpdate = true;
  }, [materials]);

  return (
    <group ref={group} {...props} dispose={null} position={[0.3, 1.4, -0.2]} rotation={[0, Math.PI / 30, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.7}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials['01___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_1.geometry} material={materials['01___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_2.geometry} material={materials['01___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_3.geometry} material={materials['01___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_4.geometry} material={materials['01___Default']} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_5.geometry} material={materials['01___Default']} />
          {/* Video screen overlay: position and scale to fit the monitor */}
          <mesh position={[-0.156, 0.176, isMobile ? -0.231 : -0.2338]} rotation={[0, 0, 0]} scale={[1.4, 0.84, 1.5]}>
            <planeGeometry args={[1, 1]} />
            <meshBasicMaterial map={videoTexture} toneMapped={false} />
          </mesh>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/scene.gltf');

export default DemoComputer;